import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Our Data — How We Source & Classify Indian Restaurants',
  description: 'How Indian Restaurants in USA sources, cleans, classifies, and publishes restaurant data across the United States.',
};

export default function OurDataPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <nav className="text-sm text-gray-500 mb-6 flex gap-1.5 flex-wrap">
        <Link href="/" className="hover:text-spice">Home</Link>
        <span>/</span>
        <Link href="/about" className="hover:text-spice">About</Link>
        <span>/</span>
        <span className="text-gray-800 font-medium">Our Data</span>
      </nav>

      <h1 className="text-3xl font-bold text-maroon mb-2">Our Data</h1>
      <p className="text-gray-600 mb-10">
        Transparency about how we source, process, and classify restaurant information.
      </p>

      <div className="space-y-10">
        <section>
          <h2 className="text-xl font-bold text-maroon mb-3">Data Sources</h2>
          <p className="text-gray-700 leading-relaxed">
            Core restaurant data (name, address, phone, website, hours, ratings, and photos) is sourced
            from Google Places via Outscraper. This gives us high-quality, frequently updated data
            consistent with what users already see on Google Maps.
          </p>
          <p className="text-gray-700 leading-relaxed mt-3">
            <strong>We do not fabricate, invent, or misrepresent restaurant information.</strong>
            Ratings and review counts are sourced directly from Google and linked back to Google Maps
            for verification.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-maroon mb-3">Regional Cuisine Classification</h2>
          <p className="text-gray-700 leading-relaxed">
            Cuisine tags are generated by Claude AI (Anthropic) using the restaurant name, description,
            and known keyword signals. Classification is conservative — we only assign a tag when there
            is clear evidence. An empty cuisine tag is better than a wrong one.
          </p>
          <p className="text-gray-700 leading-relaxed mt-3">
            Tags are pipe-separated and can include multiple values (e.g., a restaurant can be both
            North Indian and Indo-Chinese). We classify against a fixed taxonomy of 12 regional styles.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-maroon mb-3">Dietary Classification</h2>
          <p className="text-gray-700 leading-relaxed">
            Dietary tags (Jain, pure vegetarian, vegan, halal, gluten-free) are assigned conservatively
            based on explicit signals in the restaurant name or description. We do not infer dietary
            suitability from cuisine type alone.
          </p>
          <p className="text-gray-700 leading-relaxed mt-3">
            <strong>Always confirm directly with the restaurant</strong> before relying on dietary tags
            for health or religious compliance. Restaurant menus and practices change.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-maroon mb-3">Phased Publishing</h2>
          <p className="text-gray-700 leading-relaxed">
            We publish restaurants in priority order based on data quality, rating, review count, and
            cuisine/dietary enrichment completeness. Not all restaurants in our dataset are currently
            visible. We add approximately 100 new listings per week.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-maroon mb-3">Hidden Gem Algorithm</h2>
          <p className="text-gray-700 leading-relaxed">
            A restaurant is flagged as a &quot;hidden gem&quot; if it meets all three criteria:
            rating ≥ 4.5 stars, fewer than 200 Google reviews, and currently operational.
            This combination identifies genuinely exceptional restaurants that haven&apos;t been
            discovered by mainstream audiences yet.
          </p>
        </section>

        <div className="bg-cream border border-saffron/30 rounded-xl p-6">
          <h2 className="font-bold text-maroon mb-2">Report Incorrect Data</h2>
          <p className="text-sm text-gray-700">
            If you find incorrect information about a restaurant (wrong hours, closed permanently, etc.),
            please <Link href="/contact" className="text-spice hover:underline">contact us</Link>.
            We review all corrections within 48 hours.
          </p>
        </div>
      </div>
    </div>
  );
}
