export const ANCHOR_TEXT = {
  indianRestaurants: 'Indian restaurants',
  bestIndianFood: 'best Indian food',
  indianRestaurantNearMe: 'Indian restaurant near me',
  northIndian: 'North Indian restaurants',
  southIndian: 'South Indian restaurants',
  biryani: 'biryani restaurants',
  dosaRestaurants: 'dosa restaurants',
  jainRestaurants: 'Jain-friendly Indian restaurants',
  pureVegIndian: 'pure vegetarian Indian restaurants',
  halalIndian: 'halal Indian restaurants',
  veganIndian: 'vegan Indian restaurants',
  hiddenGems: 'hidden gem Indian restaurants',
  indoChinese: 'Indo-Chinese restaurants',
  gujaratiThali: 'Gujarati thali restaurants',
  hyderabadiDum: 'Hyderabadi dum biryani',
  edisonNJ: 'Indian restaurants in Edison, NJ',
  bayArea: 'Indian restaurants in the Bay Area',
  devonAveChicago: 'Indian restaurants on Devon Avenue, Chicago',
  hillcroaftHouston: 'Indian restaurants in Houston Hillcroft',
} as const;
